### ISSUE TITLE
Multi-world support

### ISSUE THREAD

**Issue by LordRalex** [LordRalex/TotalPermissions#11]
Add in multi-world support

**Comment by 1Rogue** [comment]
https://github.com/AE97/TotalPermissions/commit/155688d949a4c4f70b2d1bcb4c528ddcb4d82f9d
https://github.com/AE97/TotalPermissions/commit/912697d1547a086b9320f32c83db93ffc487dbaa

**Comment by 1Rogue** [comment]
https://github.com/AE97/TotalPermissions/commit/fce18381963ce198d9ba6923a3f1eb8fe35841d3

**Comment by 1Rogue** [comment]
https://github.com/AE97/TotalPermissions/commit/b84c2028781433370a19c8ce0107974e5d4b9581
https://github.com/AE97/TotalPermissions/commit/33cda950cdfcf118283ba6011ec4812bb9aadf0d

**Comment by 1Rogue** [comment]
https://github.com/AE97/TotalPermissions/commit/83c4c2a63b520cbdb38217a0a7af322c0d6c7590
