### ISSUE TITLE
Multi-lingual

### ISSUE THREAD

**Issue by LordRalex** [LordRalex/TotalPermissions#12]
Let's add langauges \o/

**Comment by 1Rogue** [comment]
Perhaps drafting out to other people for this? Might take some time to do this. I can cover french though. I know some people who are good with spanish as well.

**Comment by 1Rogue** [comment]
https://github.com/AE97/TotalPermissions/commit/51601d0316c59ff4769ae5f59b2d58658e035d28
https://github.com/AE97/TotalPermissions/commit/0b2efaf4476be301ad0d6e39e84f565fbbcc4998
https://github.com/AE97/TotalPermissions/commit/417b4d8ea1a277fa5273c36799d444f3513d2122
https://github.com/AE97/TotalPermissions/commit/8275476f28bf065e2763836c4cee277f722b5952

Currently supports Finnish, Swedish, and obviously English.

**Comment by 1Rogue** [comment]
https://github.com/AE97/TotalPermissions/commit/778f60826ad2cd39d12251bbb85ae4fe9dad4339
Now supports Dutch

**Comment by 1Rogue** [comment]
https://github.com/AE97/TotalPermissions/commit/c1f825d0e22eb2a6207f6be2f3ab785519d30462
Lang resources are on the git repo instead now, with english compiled in.

**Comment by LordRalex** [comment]
https://github.com/AE97/TotalPermissions/commit/6e1cfef93dce649a31937435208bd35303f1faa3
