### ISSUE TITLE
Perm dumps

### ISSUE THREAD

**Issue by LordRalex** [LordRalex/TotalPermissions#15]
Ability to dump permission based on command, plugin, and player.

**Comment by 1Rogue** [comment]
like dumping specific segments to a txt file, or...?

**Comment by LordRalex** [comment]
https://github.com/AE97/TotalPermissions/commit/40b0d195e0095a534e73001bc62fa9d8ef10a990

**Comment by LordRalex** [comment]
https://github.com/AE97/TotalPermissions/commit/73f420d1fdb4ceb69e6ea527ad5b389379de0ae5
