### ISSUE TITLE
Custom Denial Message

### ISSUE THREAD

**Issue by 1Rogue** [LordRalex/TotalPermissions#17]
Leave a custom message when a permission is denied, rather than the default denial from bukkit.

Or better yet, make it configurable

**Comment by 1Rogue** [comment]
Hmm, seems that there is a denial message. looks like the issue when I tested is that we don't control bukkit's commands yet.

**Comment by LordRalex** [comment]
You cannot access those commands using Bukkit-API, only way is to set a new executor for them. And even then some are not override-able.

**Comment by 1Rogue** [comment]
Looking here: https://github.com/codename-B/bPermissions/blob/master/src/de/bananaco/bpermissions/imp/BukkitCompat.java#L50

**Comment by LordRalex** [comment]
Not seeing it. Only see perm stuff, not denial messages

**Comment by LordRalex** [comment]
Although the way he does perms is a ton better than the way i am doing it now.
