### ISSUE TITLE
Adding Perms for OPs

### ISSUE THREAD

**Issue by 1Rogue** [LordRalex/TotalPermissions#26]
Under the "special" category, perhaps we can add custom group for OPs.

**Comment by LordRalex** [comment]
Possible, very easy.

**Comment by LordRalex** [comment]
Pushing to 0.3

**Comment by LordRalex** [comment]
Nvm, in 0.2 now
https://github.com/AE97/TotalPermissions/commit/3ce95c240d382691e2499a45caf6e049cc178069
