### ISSUE TITLE
section returned null in PermissionGroup class

### ISSUE THREAD

**Issue by 1Rogue** [LordRalex/TotalPermissions#8]
This renders things like checking for the default group or other values useless.

**Comment by 1Rogue** [comment]
stacktrace: http://pastie.org/pastes/6407921/text

**Comment by 1Rogue** [comment]
closed because we're both stupid

**Comment by LordRalex** [comment]
https://github.com/AE97/TotalPermissions/commit/7eacb2e01a86094fb38879206bd0c8aafdce7e86
